package constants

const LEFT_GROUP = "["
const RIGHT_GROUP = "]"
const HOLD = "_"
const REST = "~"
const MODIFIER_ARPEGGIO = "@"
const MODIFIER_VELOCITY = "!"
const MODIFIER_TRANSPOSE = "$"
const MODIFIER_PROBABILITY = "?"
const MODIFIER_NOTE = "#"
const MODIFIER_GATE = "%"
const SYMBOL_CHAIN = "+"
const MODIFIERS = MODIFIER_ARPEGGIO + MODIFIER_VELOCITY + MODIFIER_TRANSPOSE + MODIFIER_PROBABILITY + MODIFIER_GATE + MODIFIER_NOTE
